const mongoose = require("mongoose");
const empSchema = new mongoose.Schema({
    name: { type: String },
    fathername: { type: String },
    DoB: { type: String },
    gender: { type: String },
    phone1: { type: Number },
    phone2: { type: Number },
    localaddress: { type: String },
    parmanentaddress: { type: String },
    nationality : { type: String },
    reference1 :{type: String},
    reference1phone:{type:Number},
    reference2:{type:String},
    reference2phone:{type:Number},
    maritalstatus:{type:String},
    accountholdername:{type:String},
    accountnumber:{type:String},
    bankname:{type:String},
    branch:{type:String},
    bankcode:{type:String},
    empid:{type:String},
    department:{type:String},
    BasicSalary:{type:String},
    dateofjoining:{type:String},
    designation:{type:String},
    dateofleaving:{type:String},
    accountholdername:{type:String},
    accountnumber:{type:String},
    bankname:{type:String},
branch:{type:String},
bankcode:{type:String},
offerletter:{type:String},
joiningletter:{type:String}
})
module.exports = mongoose.model('emp', empSchema)
